version: "3.8"

services:
  web:
    build: .
    container_name: django_app

    working_dir: /smart_calendar/smart_calendar

    ports:
      - "8000:8000"

    volumes:
      - .:/smart_calendar
    env_file:
      - ../.env

    command: python manage.py runserver 0.0.0.0:8000

    extra_hosts:
      - "host.docker.internal:host-gateway"
